# Generated by Django 4.0 on 2022-01-10 23:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_delete_customuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_category', models.CharField(choices=[('USD', 'USD'), ('GBP', 'GBP'), ('EUR', 'EUR'), ('NGN', 'NGN')], default=0, max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='eWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, max_digits=100)),
                ('currency_type', models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.currency')),
            ],
        ),
        migrations.CreateModel(
            name='User_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('users', models.CharField(choices=[('Noobs', 'Noobs'), ('Elite', 'Elite')], default=0, max_length=15)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='fullname',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='Withdrawal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet_id', models.CharField(default=None, max_length=50)),
                ('amount', models.CharField(default=None, max_length=50)),
                ('status', models.CharField(default=None, max_length=50)),
                ('currency_types', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='accounts.currency')),
                ('user_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='accounts.user')),
                ('user_types', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='accounts.user_type')),
                ('wallet_address', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='accounts.ewallet')),
            ],
        ),
        migrations.CreateModel(
            name='UserAccountSettings',
            fields=[
                ('wallet_id', models.CharField(max_length=15, primary_key=True, serialize=False, unique=True)),
                ('currency_types', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='accounts.currency')),
                ('user_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='accounts.user')),
                ('user_types', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.user_type')),
            ],
        ),
        migrations.CreateModel(
            name='Fund_eWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=50, null=True)),
                ('currency_type', models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.currency')),
                ('user_id', models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.user')),
                ('wallet_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='accounts.useraccountsettings')),
            ],
        ),
        migrations.AddField(
            model_name='ewallet',
            name='user_id',
            field=models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.user'),
        ),
        migrations.AddField(
            model_name='ewallet',
            name='wallet_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='accounts.useraccountsettings'),
        ),
    ]
