# Generated by Django 4.0 on 2022-01-14 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userbalance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fund_ewallet',
            name='currency_type',
        ),
        migrations.RemoveField(
            model_name='fund_ewallet',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='fund_ewallet',
            name='wallet_id',
        ),
        migrations.RemoveField(
            model_name='useraccountsettings',
            name='currency_types',
        ),
        migrations.RemoveField(
            model_name='useraccountsettings',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='useraccountsettings',
            name='user_types',
        ),
        migrations.RemoveField(
            model_name='userbalance',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userbalance',
            name='user_account',
        ),
        migrations.RemoveField(
            model_name='withdrawal',
            name='currency_types',
        ),
        migrations.RemoveField(
            model_name='withdrawal',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='withdrawal',
            name='user_types',
        ),
        migrations.RemoveField(
            model_name='withdrawal',
            name='wallet_address',
        ),
        migrations.RemoveField(
            model_name='ewallet',
            name='currency_type',
        ),
        migrations.RemoveField(
            model_name='ewallet',
            name='wallet_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='fullname',
        ),
        migrations.AddField(
            model_name='ewallet',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD'), ('GBP', 'GBP'), ('EUR', 'EUR'), ('NGN', 'NGN')], default=0, max_length=15),
        ),
        migrations.AddField(
            model_name='user',
            name='types',
            field=models.CharField(choices=[('Noob', 'Noob'), ('Elite', 'Elite'), ('Admin', 'Admin')], default='Noob', max_length=15),
        ),
        migrations.DeleteModel(
            name='Currency',
        ),
        migrations.DeleteModel(
            name='Fund_eWallet',
        ),
        migrations.DeleteModel(
            name='User_type',
        ),
        migrations.DeleteModel(
            name='UserAccountSettings',
        ),
        migrations.DeleteModel(
            name='UserBalance',
        ),
        migrations.DeleteModel(
            name='Withdrawal',
        ),
    ]
