# Generated by Django 4.0 on 2022-01-15 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_fund_ewallet_currency_type_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='eWallet',
            new_name='Wallet',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='types',
            new_name='type',
        ),
    ]
