# Generated by Django 4.0 on 2022-01-15 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_rename_ewallet_wallet_rename_types_user_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='type',
            new_name='account_type',
        ),
    ]
